version: "3.9"
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin123
      DATABASE_NAME: task_manager
      DATABASE_PORT: 5432

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
